### ISSUE TITLE
Crash from callbacks, after the latest check-in

### ISSUE THREAD

**Issue by tigrangs** [hop-/Mercurius#19]
Program received signal SIGSEGV, Segmentation fault.
0x0000000000c75860 in ?? ()
(gdb) bt
#0  0x0000000000c75860 in ?? ()
#1  0x000000000042d23c in std::_Mem_fn_base<void (Core::State::*)(Core::Event*), true>::operator()<Core::Event*, void>(Core::State_, Core::Event_&&) const (

```
this=0xcaae40, __object=0xdabff0) at /usr/include/c++/5/functional:600
```
#2  0x000000000042cf72 in std::_Bind<std::_Mem_fn<void (Core::State::*)(Core::Event*)> (Core::State_, std::_Placeholder<1>)>::__call<void, Core::Event_&&, 0ul, 1ul>(std::tupleCore::Event*&&&&, std::_Index_tuple<0ul, 1ul>) (this=0xcaae40, __args=<unknown type in /home/tigrangs/Git/Mercurius/mercurius-d, CU 0xf584d, DIE 0x101d2f>)

```
at /usr/include/c++/5/functional:1074
```
#3  0x000000000042c68c in std::_Bind<std::_Mem_fn<void (Core::State::*)(Core::Event*)> (Core::State_, std::_Placeholder<1>)>::operator()<Core::Event_, void>(Core::Event*&&) (this=0xcaae40) at /usr/include/c++/5/functional:1133
#4  0x000000000042bdc5 in std::_Function_handler<void (Core::Event*), std::_Bind<std::_Mem_fn<void (Core::State::*)(Core::Event*)> (Core::State_, std::_Placeholder<1>)> >::_M_invoke(std::_Any_data const&, Core::Event_&&) (__functor=..., __args#0=<unknown type in /home/tigrangs/Git/Mercurius/mercurius-d, CU 0xf584d, DIE 0x1005e0>)

```
at /usr/include/c++/5/functional:1871
```
#5  0x000000000043f095 in std::function<void (Core::Event*)>::operator()(Core::Event*) const (this=0xcab360, __args#0=0xc1b550) at /usr/include/c++/5/functional:2271
#6  0x000000000043ee33 in Core::EventCreatorCore::KeyEvent::trigger (this=0xc1b550) at src/core/event.hpp:64
#7  0x00000000004381f9 in Core::Game::mainLoop (this=0x688540) at src/core/game.cpp:80
#8  0x0000000000438464 in Core::Game::start (this=0x688540) at src/core/game.cpp:112
#9  0x0000000000412423 in Assets::Mercurius::start () at src/assets/mercurius.cpp:35
#10 0x00000000004455b7 in main (argc=1, argv=0x7fffffffdff8) at src/main.cpp:12

**Comment by hop-** [comment]
It appears on  Falling to OnGround transformation.
