### ISSUE TITLE
Layer::addLogicObject did not use redefined virtual function onAddObject

### ISSUE THREAD

**Issue by hop-** [hop-/Mercurius#8]
In Layer::addLogicObject it forced to call addObject form Base::ContainerObject<LogicObject> parent. addObject of Base::ContainerObject<LogicObject> calls virtual empty function onObjectAdding which is redefined in Layer and should be used on addObject.

**Comment by tigrangs** [comment]
maybe you mean Logic::addLogicObject instead of Layer::...?

**Comment by hop-** [comment]
Yes you are right:D

**Comment by tigrangs** [comment]
Fixed
